openapi: 3.0.1
info: 
  title: API de Consultório
  description: API Para controlar médicos e suas especialidades dentro do consultório.
  version: 1.0.0
  termsOfService: https://mockapi.io
  contact:
    name: Suporte a devs
    email: contato@example.com
    url: https://mockapi.io
  license:
    name: "Licença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.pt-br.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io
servers: 
- url: http//6096015d116f300174b29ba.mockapi.io/
  description: API de test
paths:
  /especialidades:
    get:
      summary: Recupera todas as especialidades
      security:
      - auth: []
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Especialidades"
    post:
      summary: "Cria nova especialidade"
      description: "Através desse endpoint você pode criar novas especialidades"
      requestBody:
        description: "Enviar um objeto do tipo"
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Especialidade"
                
  /especialidades/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Recupera uma entidade pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Especialidade"
        404:
          description: Especialidade nao encontrada
          content:
            application/json:
              example: "Not Found"
    delete:
      summary: Exlui uma entidade pelo ID
      responses:
        200:
          description: Removida com sucesso
          content:
            text/plain:
              schema:
                type: string
                example: "Removido com sucesso"
    put:
      summary: Atualiza uma entidade
      requestBody:
        description: "Enviar um objeto do tipo"
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        200:
          description: Atualizada com sucesso
          content:
            text/plain:
              schema:
                type: string
                example: "Atualizada com sucesso"
components:
  schemas:
    Especialidade:
      type: object
      properties:
        id:
          type: integer
        descricao:
          type: string
    Especialidades:
      type: array
      items:
        $ref: "#/components/schemas/Especialidade"
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
          